/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as CreateImport } from './routes/create'
import { Route as IndexImport } from './routes/index'
import { Route as ContactsContactidImport } from './routes/contacts/$contactid'
import { Route as ContactsEditContactidImport } from './routes/contacts/edit/$contactid'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactsContactidRoute = ContactsContactidImport.update({
  id: '/contacts/$contactid',
  path: '/contacts/$contactid',
  getParentRoute: () => rootRoute,
} as any)

const ContactsEditContactidRoute = ContactsEditContactidImport.update({
  id: '/contacts/edit/$contactid',
  path: '/contacts/edit/$contactid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/contacts/$contactid': {
      id: '/contacts/$contactid'
      path: '/contacts/$contactid'
      fullPath: '/contacts/$contactid'
      preLoaderRoute: typeof ContactsContactidImport
      parentRoute: typeof rootRoute
    }
    '/contacts/edit/$contactid': {
      id: '/contacts/edit/$contactid'
      path: '/contacts/edit/$contactid'
      fullPath: '/contacts/edit/$contactid'
      preLoaderRoute: typeof ContactsEditContactidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/error': typeof ErrorRoute
  '/contacts/$contactid': typeof ContactsContactidRoute
  '/contacts/edit/$contactid': typeof ContactsEditContactidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/error': typeof ErrorRoute
  '/contacts/$contactid': typeof ContactsContactidRoute
  '/contacts/edit/$contactid': typeof ContactsEditContactidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/error': typeof ErrorRoute
  '/contacts/$contactid': typeof ContactsContactidRoute
  '/contacts/edit/$contactid': typeof ContactsEditContactidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/error'
    | '/contacts/$contactid'
    | '/contacts/edit/$contactid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/error'
    | '/contacts/$contactid'
    | '/contacts/edit/$contactid'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/error'
    | '/contacts/$contactid'
    | '/contacts/edit/$contactid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ErrorRoute: typeof ErrorRoute
  ContactsContactidRoute: typeof ContactsContactidRoute
  ContactsEditContactidRoute: typeof ContactsEditContactidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ErrorRoute: ErrorRoute,
  ContactsContactidRoute: ContactsContactidRoute,
  ContactsEditContactidRoute: ContactsEditContactidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/error",
        "/contacts/$contactid",
        "/contacts/edit/$contactid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/contacts/$contactid": {
      "filePath": "contacts/$contactid.tsx"
    },
    "/contacts/edit/$contactid": {
      "filePath": "contacts/edit/$contactid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
